description: Core components and triggers for building with SuperPlane.
triggers:
    - name: start
      label: Manual Run
      description: Manually start a run
      configuration:
        - name: customName
          label: Run title (optional)
          type: string
          required: false
          description: Optional run title. Supports expressions like {{ $.data }}.
      example_data: pkg/triggers/start/example_data.json
    - name: webhook
      label: Webhook
      description: Trigger a run with a webhook
      configuration:
        - name: authentication
          label: Authentication
          type: select
          required: true
          description: ""
        - name: customName
          label: Run title (optional)
          type: string
          required: false
          description: Set a run title using a template. You can use expressions like {{ $.data }}.
      example_data: pkg/triggers/webhook/example_data.json
    - name: schedule
      label: Schedule
      description: Trigger a run on a schedule
      configuration:
        - name: type
          label: Frequency
          type: select
          required: true
          description: ""
        - name: timezone
          label: Timezone
          type: timezone
          required: false
          description: 'Timezone offset for scheduling calculations (default: your current timezone)'
        - name: minutesInterval
          label: Minutes between triggers
          type: number
          required: false
          description: Number of minutes between triggers (1-59)
        - name: hoursInterval
          label: Hours between triggers
          type: number
          required: false
          description: Number of hours between triggers (1-23)
        - name: daysInterval
          label: Days between triggers
          type: number
          required: false
          description: Number of days between triggers (1-31)
        - name: weeksInterval
          label: Weeks between triggers
          type: number
          required: false
          description: Number of weeks between triggers (1-52)
        - name: monthsInterval
          label: Months between triggers
          type: number
          required: false
          description: Number of months between triggers (1-24)
        - name: dayOfMonth
          label: Trigger on day of the month
          type: number
          required: false
          description: Day of the month (1-31)
        - name: weekDays
          label: Trigger on days of the week
          type: multi-select
          required: false
          description: Select which days of the week to trigger
        - name: hour
          label: Trigger at hour
          type: number
          required: false
          description: Hour of the day (0-23)
        - name: minute
          label: Trigger at minute
          type: number
          required: false
          description: Minute of the hour (0-59)
        - name: cronExpression
          label: Cron Expression
          type: cron
          required: false
          description: 'Cron expression in 5-field (e.g., ''30 14 * * MON-FRI'') or 6-field (e.g., ''0 30 14 * * MON-FRI'') format. Valid wildcards: * , - /'
        - name: customName
          label: Run title (optional)
          type: string
          required: false
          description: Optional run title template. Supports expressions like {{ $.data }}.
      example_data: pkg/triggers/schedule/example_data.json

components:
    - name: approval
      label: Approval
      description: Collect approvals on events
      configuration:
        - name: items
          label: Approvers
          type: list
          required: true
          description: List of users, groups, or roles who must approve before the workflow continues
      example_output: pkg/components/approval/example_output.json
    - name: filter
      label: Filter
      description: Filter events based on their content
      configuration:
        - name: expression
          label: Filter Expression
          type: expression
          required: true
          description: Boolean expression to filter data
      example_output: pkg/components/filter/example_output.json
    - name: http
      label: HTTP Request
      description: Make HTTP requests
      configuration:
        - name: method
          label: Method
          type: select
          required: true
          description: ""
        - name: url
          label: URL
          type: string
          required: true
          description: ""
        - name: queryParams
          label: Query Params
          type: list
          required: false
          description: Query parameters to append to the URL
        - name: headers
          label: Headers
          type: list
          required: false
          description: Custom headers to send with this request
        - name: contentType
          label: Body
          type: select
          required: false
          description: Body content type for POST, PUT, and PATCH requests
        - name: json
          label: JSON Payload
          type: object
          required: false
          description: The JSON object to send as the request body
        - name: formData
          label: Form Data
          type: list
          required: false
          description: Key-value pairs to send as form data
        - name: text
          label: Text Payload
          type: text
          required: false
          description: Plain text to send as the request body
        - name: xml
          label: XML Payload
          type: xml
          required: false
          description: XML content to send as the request body
        - name: successCodes
          label: Overwrite success definition
          type: string
          required: false
          description: Comma-separated list of success status codes (e.g., 200, 201, 2xx). Leave empty for default 2xx behavior
        - name: timeoutStrategy
          label: Set Timeout and Retries
          type: select
          required: false
          description: Configure timeout and retry behavior for failed requests
        - name: timeoutSeconds
          label: Timeout (seconds)
          type: number
          required: false
          description: Timeout in seconds for each request attempt
        - name: retries
          label: Retries
          type: number
          required: false
          description: Number of retry attempts. Wait longer after each failed attempt (timeout capped to 120s)
      example_output: pkg/components/http/example_output.json
    - name: if
      label: If
      description: Route events based on expression
      configuration:
        - name: expression
          label: ""
          type: expression
          required: true
          description: Boolean expression to evaluate
      example_output: pkg/components/if/example_output.json
    - name: merge
      label: Merge
      description: Merge multiple upstream inputs and forward
      configuration:
        - name: executionTimeout
          label: Execution Timeout
          type: object
          required: false
          description: ""
        - name: stopIfExpression
          label: Stop if
          type: expression
          required: false
          description: When true, stop waiting and finish immediately.
      example_output: pkg/components/merge/example_output.json
    - name: noop
      label: No Operation
      description: Just pass events through without any additional processing
      example_output: pkg/components/noop/example_output.json
    - name: time_gate
      label: Time Gate
      description: Route events based on time conditions - include or exclude specific time windows
      configuration:
        - name: mode
          label: Mode
          type: select
          required: true
          description: ""
        - name: days
          label: Days of Week
          type: multi-select
          required: false
          description: ""
        - name: startDayInYear
          label: Start Day (MM/DD)
          type: day-in-year
          required: false
          description: Start day in MM/DD format (e.g., 12/25 for Christmas)
        - name: startTime
          label: Start Time (HH:MM)
          type: time
          required: true
          description: Start time in HH:MM format (24-hour), e.g., 09:30
        - name: endDayInYear
          label: End Day (MM/DD)
          type: day-in-year
          required: false
          description: End day in MM/DD format (e.g., 01/01 for New Year)
        - name: endTime
          label: End Time (HH:MM)
          type: time
          required: true
          description: End time in HH:MM format (24-hour), e.g., 17:30
        - name: timezone
          label: Timezone
          type: select
          required: true
          description: 'Timezone offset for time-based calculations (default: UTC)'
      example_output: pkg/components/timegate/example_output.json
    - name: wait
      label: Wait
      description: Wait for a certain amount of time
      configuration:
        - name: mode
          label: Wait Mode
          type: select
          required: true
          description: ""
        - name: waitFor
          label: Wait for...
          type: string
          required: false
          description: |-
            Component will wait for a fixed amount of time before emitting the event forward.

            Supports expressions and expects integer.

            Example expressions:
            {{$.wait_time}}
            {{$.wait_time + 5}}
            {{$.status == "urgent" ? 0 : 30}}
        - name: unit
          label: Unit
          type: select
          required: false
          description: Time unit for the interval
        - name: waitUntil
          label: Wait until
          type: string
          required: false
          description: |-
            Component will countdown until the provided date/time before emitting an event forward.

            Supports expressions and expects date in [ISO 8601](https://www.timestamp-converter.com/) format.

            Example expressions:
            {{$.run_time}}
            {{$.run_time.In(timezone("UTC"))}}
            {{$.run_time + duration("48h")}}
      example_output: pkg/components/wait/example_output.json